
package Pantallas;

import Controlador.Controlador;


/**
 *
 * @author AudelGS
 */


public class MenuCentral extends javax.swing.JFrame {
    
    private Controlador controlador;
    private InventarioDeLibros inventario;
    private LibrosModel modelLibros;
    private AgregarLibros Alibros;
    
    
    
    

    
    public MenuCentral() {
        controlador = new Controlador();
        modelLibros = new LibrosModel(controlador);
        inventario = new InventarioDeLibros(this, true);
        inventario.setoController(controlador);
        
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Menu Central");
        
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTablaPrestamos = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuInventario = new javax.swing.JMenuItem();
        ListaDeUsuarios = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        Inventario = new javax.swing.JMenuItem();
        jAgregarLibro = new javax.swing.JMenuItem();
        jEditarLibro = new javax.swing.JMenuItem();
        jEliminarLibro = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AgregarUsuario = new javax.swing.JMenuItem();
        EditarUsuario = new javax.swing.JMenuItem();
        EliminarUsuario = new javax.swing.JMenuItem();
        Acceso = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        TurorialPrograma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablaPrestamos.setViewportView(jTable1);

        btnSalir.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\AudelGS\\Documents\\NetBeansProjects\\BibliotecaCentral\\build\\classes\\Icons\\salir-de-mi-perfil-icono-3964-16.png")); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jButton2.setText("Entregar");

        jButton3.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jButton3.setText("Editar");

        jButton4.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jButton4.setText("Acceso");

        jButton5.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jButton5.setText("Renovar");

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu4.setBorder(null);
        jMenu4.setIcon(new javax.swing.ImageIcon("C:\\Users\\AudelGS\\Documents\\NetBeansProjects\\BibliotecaCentral\\build\\classes\\Icons\\Menu.png")); // NOI18N
        jMenu4.setText("Menu");

        jMenuInventario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuInventario.setText("Inventario de Libros");
        jMenuInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInventarioActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuInventario);

        ListaDeUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        ListaDeUsuarios.setText("Lista de Usuarios");
        ListaDeUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaDeUsuariosActionPerformed(evt);
            }
        });
        jMenu4.add(ListaDeUsuarios);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem3.setText("Imprimir");
        jMenu4.add(jMenuItem3);

        Ayuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        Ayuda.setText("Ayuda");
        Ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaActionPerformed(evt);
            }
        });
        jMenu4.add(Ayuda);

        jMenuBar1.add(jMenu4);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\AudelGS\\Documents\\NetBeansProjects\\BibliotecaCentral\\build\\classes\\Icons\\biblioteca-icono-3766-32.png")); // NOI18N
        jMenu1.setText("Biblioteca");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Inventario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        Inventario.setText("Inventario");
        Inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioActionPerformed(evt);
            }
        });
        jMenu1.add(Inventario);

        jAgregarLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jAgregarLibro.setText("Agregar Libro");
        jAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarLibroActionPerformed(evt);
            }
        });
        jMenu1.add(jAgregarLibro);

        jEditarLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jEditarLibro.setText("Editar Libro");
        jEditarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarLibroActionPerformed(evt);
            }
        });
        jMenu1.add(jEditarLibro);

        jEliminarLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jEliminarLibro.setText("Eliminar Libro");
        jEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarLibroActionPerformed(evt);
            }
        });
        jMenu1.add(jEliminarLibro);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\AudelGS\\Documents\\NetBeansProjects\\BibliotecaCentral\\build\\classes\\Icons\\Usuarios.png")); // NOI18N
        jMenu2.setText("Usuarios");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        AgregarUsuario.setText("Agregar Usuario");
        AgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(AgregarUsuario);

        EditarUsuario.setText("Editar Usuario");
        EditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(EditarUsuario);

        EliminarUsuario.setText("Eliminar Usuario");
        EliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(EliminarUsuario);

        Acceso.setText("Acceso");
        Acceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccesoActionPerformed(evt);
            }
        });
        jMenu2.add(Acceso);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\AudelGS\\Documents\\NetBeansProjects\\BibliotecaCentral\\build\\classes\\Icons\\libro-se-icono-3669-32.png")); // NOI18N
        jMenu3.setText("Prestamos");
        jMenuBar1.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon("C:\\Users\\AudelGS\\Documents\\NetBeansProjects\\BibliotecaCentral\\build\\classes\\Icons\\Acerca de....png")); // NOI18N
        jMenu5.setText("Ayuda");

        TurorialPrograma.setText("Tutorial Programa");
        TurorialPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TurorialProgramaActionPerformed(evt);
            }
        });
        jMenu5.add(TurorialPrograma);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(20, 20, 20)
                        .addComponent(jButton3)
                        .addGap(20, 20, 20)
                        .addComponent(jButton5)
                        .addGap(20, 20, 20)
                        .addComponent(jButton4))
                    .addComponent(jTablaPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addGap(1, 1, 1)
                .addComponent(jTablaPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jMenuInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInventarioActionPerformed
      inventario.mostrarDialogo();

        modelLibros.fireTableDataChanged();
    }//GEN-LAST:event_jMenuInventarioActionPerformed

    private void InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioActionPerformed
        inventario.mostrarDialogo();

        modelLibros.fireTableDataChanged();
    }//GEN-LAST:event_InventarioActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarLibroActionPerformed
      inventario.mostrarDialogo();

        modelLibros.fireTableDataChanged();
       
    }//GEN-LAST:event_jAgregarLibroActionPerformed

    private void jEditarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarLibroActionPerformed
        inventario.mostrarDialogo();

        modelLibros.fireTableDataChanged();
    }//GEN-LAST:event_jEditarLibroActionPerformed

    private void jEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarLibroActionPerformed
        inventario.mostrarDialogo();

        modelLibros.fireTableDataChanged();
    }//GEN-LAST:event_jEliminarLibroActionPerformed

    private void AgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUsuarioActionPerformed
        
    }//GEN-LAST:event_AgregarUsuarioActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
       
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void ListaDeUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaDeUsuariosActionPerformed
        
    }//GEN-LAST:event_ListaDeUsuariosActionPerformed

    private void EditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarUsuarioActionPerformed
        
    }//GEN-LAST:event_EditarUsuarioActionPerformed

    private void EliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuarioActionPerformed
        ;
    }//GEN-LAST:event_EliminarUsuarioActionPerformed

    private void AccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccesoActionPerformed
        
    }//GEN-LAST:event_AccesoActionPerformed

    private void TurorialProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TurorialProgramaActionPerformed
        Ayuda inv= new Ayuda();
        inv.setVisible(true);
        dispose();
    }//GEN-LAST:event_TurorialProgramaActionPerformed

    private void AyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaActionPerformed
        Ayuda inv= new Ayuda();
        inv.setVisible(true);
        dispose();
    }//GEN-LAST:event_AyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCentral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Acceso;
    private javax.swing.JMenuItem AgregarUsuario;
    private javax.swing.JMenuItem Ayuda;
    private javax.swing.JMenuItem EditarUsuario;
    private javax.swing.JMenuItem EliminarUsuario;
    private javax.swing.JMenuItem Inventario;
    private javax.swing.JMenuItem ListaDeUsuarios;
    private javax.swing.JMenuItem TurorialPrograma;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuItem jAgregarLibro;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenuItem jEditarLibro;
    private javax.swing.JMenuItem jEliminarLibro;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuInventario;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jTablaPrestamos;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
